FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean install
FROM tomcat:latest
COPY --from=build /app/target/app.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD ["catalina.sh", "run"]




